language: node_js
node_js: 
  - "stable"
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5432
    - DB_NAME=teamwork_test
    - DB_USER=vrxlqfmbilgtpd
install:
  - npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"
  - psql --dbname=$DB_NAME --file=testdb/schema.sql
  - knex seed:run --env staging
script:
  - npm test

