language: node_js
node_js: 
  - "stable"
env:
  - NODE_ENV="development"
  - NODE_ENV="production";SESSION_SECRET="7ot"
services:
  - postgresql
install:
  - npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -f ./testdb/teamwork.sql -d travis_ci_test
script:
  - npm test