const { Pool } = require('pg');
const cloudinary = require('cloudinary').v2;
const fs = require('fs');


cloudinary.config({
  cloud_name: process.env.CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
});

//console.log('cloud', cloudinary.config())


exports.createGif = (req, res) => {

  //const url = req.protocol + '://' + req.get('host') + '/' + req.file.originalname; Cloudinary can't upload from localhost
  //const path = 'images/' + req.file.filename;
  // File upload (example for promise api)
  console.log('req1' ,req.file)
  cloudinary.uploader.upload(req.file.path, { tags: 'gifs' })
  .then(function (image) {
    console.log();
    console.log("** File Upload (Promise)");
    console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
    console.log("* " + image.public_id);
    console.log("* " + image.url);
    res.status(201).json({
      'image_id': image.public_id,
      'imageUrl': image.url
    })
  })
  .then(()=> {
    fs.unlink('images/' + req.file.filename, () => {
      console.log('Deleted uploaded file from images/!')
    });
  })
  .catch(function (err) {
    console.log();
    console.log("** File Upload (Promise)");
    if (err) { console.warn(err); }
  });
}
